name: Deploy to RStudio Connect

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    container:
      image: rocker/verse:4.2.3

    steps:

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies from cran
      run: install2.r --error rsconnect shinyWidgets shinythemes readxl fs dplyr tidyr stringr BH jpeg anytime survminer survival KMsurv MatrixModels RcppEigen SparseM abind car carData corrplot cowplot exactRankTests knitr DT pak

    - name: make manuscript
      run: Rscript -e "library(knitr); knit('manuscript/result.qmd')"
    
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.2
      with:
            # Artifact name
          name: survivalresult # optional, default is artifact
          # A file, directory or wildcard pattern that describes what to upload
          path: manuscript/
          retention-days: 3 # optional


    - name: Deploy to RStudio Connect
      run: |
        pak::pak("rainoffallingstar/mellon")
        library(rsconnect)
        rsconnect::setAccountInfo(name="${{ secrets.RSCONNECT_ACCOUNT }}", 
                                  token="${{ secrets.RSCONNECT_TOKEN }}", 
                                  secret="${{ secrets.RSCONNECT_SECRET }}")
        rsconnect::deployApp(appDir = getwd())
      shell: Rscript {0}
